# Generated by Django 3.2.7 on 2021-10-24 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingsearch', '0002_alter_housing_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_text', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('review_text', models.CharField(max_length=300)),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housingsearch.housing')),
            ],
        ),
    ]
