# Generated by Django 3.2.7 on 2021-10-29 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housingsearch', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='housing',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='housingsearch.housing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='review_text',
            field=models.CharField(default='', max_length=300),
        ),
    ]
