# Generated by Django 3.2.7 on 2021-11-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingsearch', '0015_auto_20211106_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='address',
            field=models.CharField(max_length=3000),
        ),
    ]
