# Generated by Django 3.2.7 on 2021-11-11 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('housingsearch', '0016_alter_housing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='housing/'),
            preserve_default=False,
        ),
    ]
