# Generated by Django 3.2.7 on 2021-11-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingsearch', '0017_housing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housing',
            name='image',
            field=models.ImageField(upload_to='housing'),
        ),
    ]
