# Generated by Django 3.2.7 on 2021-11-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingsearch', '0020_auto_20211112_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
