# Generated by Django 3.2.7 on 2021-11-13 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housingsearch', '0021_alter_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='city',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='state',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zip',
        ),
    ]
