# Generated by Django 3.2.7 on 2021-11-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housingsearch', '0022_auto_20211112_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default=' ', max_length=300, primary_key=True, serialize=False, unique=True),
        ),
    ]
